---
title: "Air Pollution" #replace the title with something short and catchy to represent your project
subtitle: "Asheela Magwili's Data Science Portfolio"
output:
  html_document:
    df_print: paged
---

## Abstract

I am interested in looking into air pollution and the behavior of air pollutants over time. It would be interesting to see how this research relates to topics like climate change, wildlife, and depletion of the atmosphere.

### 1. Discovery and Data Preparation

In the first deliverable, the data is introduced, cleaned, and processed. This phase focuses on understanding the data and making it readable for others to understand as well.


Access the first deliverable here: [`DELIVERABLE 1`](https://introdsci.github.io/DataScience-asheelamagwili/deliverable1)

### 2. Model Planning and Building

In the second deliverable, supplemental data is introduced that focuses on different inventory sectors. These sectors includes Energy, Agriculture, Industrial, Waste, and Forestry. A model of this data can be used to predict the behavior of greenhouse gasses.

Access the second deliverable here: [`DELIVERABLE 2`](https://introdsci.github.io/DataScience-asheelamagwili/deliverable2)

### 3. Results and Operationalization

In the final deliverable, we conclude the study with our findings and operationalize how this study may impact society. Although, the study wasn't a good fit for the model chosen the overall idea and social implications of this type of study is still important to note.

Access the third deliverable here: [`DELIVERABLE 3`](https://introdsci.github.io/DataScience-asheelamagwili/deliverable3)

